version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: monthly
