name: Lint
on: pull_request

jobs:
  alex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: reviewdog/action-alex@v1
        with:
          reporter: github-pr-review

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review

  markdown:
    name: markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: reviewdog/action-markdownlint@v0
        with:
          level: warning
          markdownlint_flags: website/docs/**/*.md
          reporter: github-pr-review

  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: reviewdog/action-misspell@v1
        with:
          level: warning
          reporter: github-pr-review
